//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropyourcomplain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddComplain
    {
        public int Id { get; set; }
        public string ComplainType { get; set; }
        public string ComplainArea { get; set; }
        public string RoadNumber { get; set; }
        public string ComplainDetails { get; set; }
        public string Photo { get; set; }
        public string Compailer_Name { get; set; }
        public string Cotract_Number { get; set; }
        public string Email { get; set; }
    }
}
